#include "app_config.h"

const app_config_t g_app_config = {
    .output_count = DONDER_OUTPUT_COUNT,
    .pin_output_count = DONDER_PIN_OUTPUT_COUNT,
    .pixels_per_output = DONDER_PIXELS_PER_OUTPUT,
    .words_per_frame = DONDER_WORDS_PER_FRAME,
    .default_active_output_count = DONDER_DEFAULT_ACTIVE_OUTPUT_COUNT,
    .default_strand_pixel_count = DONDER_DEFAULT_STRAND_PIXEL_COUNT,
    .output_invert_mask = DONDER_OUTPUT_INVERT_MASK,
    .e131_port = DONDER_E131_PORT,
    .first_universe = DONDER_FIRST_UNIVERSE,
    .mac = {DONDER_PL_MAC0, DONDER_PL_MAC1, DONDER_PL_MAC2, DONDER_PL_MAC3, DONDER_PL_MAC4, DONDER_PL_MAC5},
    .ip = {DONDER_PL_BOARD_IP0, DONDER_PL_BOARD_IP1, DONDER_PL_BOARD_IP2, DONDER_PL_BOARD_IP3},
    .netmask = {DONDER_PL_NETMASK_IP0, DONDER_PL_NETMASK_IP1, DONDER_PL_NETMASK_IP2, DONDER_PL_NETMASK_IP3},
    .gateway = {DONDER_PL_GATEWAY_IP0, DONDER_PL_GATEWAY_IP1, DONDER_PL_GATEWAY_IP2, DONDER_PL_GATEWAY_IP3},
    .host_test_ip = {DONDER_HOST_TEST_IP0, DONDER_HOST_TEST_IP1, DONDER_HOST_TEST_IP2, DONDER_HOST_TEST_IP3},
};
